# A sample/default configuration file suitable for a holoport
storage:
    install_partition: /dev/sda1
    persist_partition: /dev/sda2
network:
    nameservers:
    interfaces:
        # Use the onboard controller, with DHCP
        - identifier: !pci_address
            address: "0000:01:00.0"
            #address: "0000:00:03.0"
          static_addresses:
security:
    github_usernames:
        - holosupport
    ssh_keys:
    rootpw_hash:

