# Conductor configuration template

admin_interface:
  driver:
    type: "websocket"
    port: 4444

network:
  bootstrap_service: "https://bootstrap-staging.holo.host"
  transport_pool:
    - type: "quic"
      enable_mdns: false
      enable_relaying: true
      signal_url: "wss://signal-staging.holo.host"
      ice_servers:
        - urls: ["stun:stun.cloudflare.com:3478"]
        - urls: ["stun:stun.l.google.com:19302"]

data_root_path: "/var/local/lib/holochain"
lair_root: ""