---
# Conductor configuration
admin_interfaces:
- driver:
    type: websocket
    port: 4444
    allowed_origins: '*'

network:
  bootstrap_url: "https://dev-test-bootstrap2.holochain.org"
  signal_url: "wss://dev-test-bootstrap2.holochain.org"
  enable_mdns: false
  enable_relaying: true

  webrtc_config:
  ice_servers:
    - urls: ["stun:stun.cloudflare.com:3478"]
    - urls: ["stun:stun.l.google.com:19302"]

  report: !json_lines
    days_retained: 30
    fetched_op_interval_s: 300

data_root_path: "/var/local/lib/holochain"

keystore:
  type: lair_server_in_proc
  lair_root: "/var/local/lib/holochain/ks"
