# Docker Compose configuration for Holochain 0.6.0-dev-go-pion testing
# This image does NOT require log-collector (base for unyt)

services:
  edgenode-hc-0.6.0-dev-go-pion:
    image: ${EDGENODE_IMAGE:-local-edgenode-hc-0.6.0-dev-go-pion}
    environment:
      - IMAGE_NAME=local-edgenode-hc-0.6.0-dev-go-pion
    volumes:
      - edgenode-data:/data
      - edgenode-logs:/data/logs
    networks:
      - test-net
    healthcheck:
      test: ["CMD", "pgrep", "holochain"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s