name: Build HolOS ISO

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest-m

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          holos/rust/holos-config/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache Buildroot downloads
      uses: actions/cache@v4
      with:
        path: holos/dl
        key: ${{ runner.os }}-buildroot-dl-${{ hashFiles('holos/Makefile', 'holos/holos-buildroot-2025.08.config') }}
        restore-keys: |
          ${{ runner.os }}-buildroot-dl-

    - name: Cache Buildroot output
      uses: actions/cache@v4
      with:
        path: holos/output
        key: ${{ runner.os }}-buildroot-out-${{ hashFiles('holos/Makefile', 'holos/holos-buildroot-2025.08.config', 'holos/kernel-config-x86_64.config') }}
        restore-keys: |
          ${{ runner.os }}-buildroot-out-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget unzip libncurses5-dev libssl-dev bc bison flex libelf-dev libssl-dev make musl-tools
        sudo apt-get clean  # Clear apt cache to free space

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Cleanup temp files before build
      run: |
        sudo rm -rf /tmp/*
        df -h  # Log disk usage

    - name: Build HolOS ISO
      run: |
        cd holos
        make clean  # Clean any local artifacts
        make iso
        df -h  # Log final disk usage

    - name: Cleanup after build
      if: always()
      run: |
        sudo rm -rf /tmp/*
        sudo apt-get clean

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: holos-iso
        path: holos/tmp/holos-*.iso
        retention-days: 5
