name: Build HolOS ISO

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget unzip libncurses5-dev libssl-dev bc bison flex libelf-dev libssl-dev make

    - name: Install Rust
      uses: dtolnay/rust-toolchain-install@v1
      with:
        toolchain: stable

    - name: Add musl target for Rust
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build HolOS ISO
      run: |
        cd holos
        make clean
        make iso

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: holos-iso
        path: holos/tmp/holos-*.iso
        retention-days: 5
