name: Build HolOS ISO

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          holos/rust/holos-config/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache Buildroot downloads
      uses: actions/cache@v4
      with:
        path: holos/dl
        key: ${{ runner.os }}-buildroot-dl-${{ hashFiles('holos/Makefile', 'holos/holos-buildroot-2025.08.config') }}
        restore-keys: |
          ${{ runner.os }}-buildroot-dl-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget unzip libncurses5-dev libssl-dev bc bison flex libelf-dev libssl-dev make musl-tools

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Build HolOS ISO
      run: |
        cd holos
        make clean
        make iso

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: holos-iso
        path: holos/tmp/holos-*.iso
        retention-days: 5
